[package]
name = "scheesim-impl"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
scheesim-macro = { path = "../scheesim-macro" }
num-traits = "*"